# Generated by Django 3.2 on 2022-04-15 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20220406_0748'),
        ('subcourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('briefing', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('closed_time', models.DateTimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('sub_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subcourse.subcourse')),
            ],
        ),
        migrations.CreateModel(
            name='StdAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads_file_std/')),
                ('is_checked', models.BooleanField(blank=True, null=True)),
                ('asgt_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subcourse.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
