# Generated by Django 3.2 on 2022-04-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20220406_0748'),
        ('subcourse', '0002_assignment_stdassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='briefing',
            new_name='description',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='uploads_file/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('sub_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subcourse.subcourse')),
            ],
        ),
    ]
