# Generated by Django 3.2 on 2022-05-09 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcourse', '0003_auto_20220417_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='sub_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subcourse.subsection'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='sub_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subcourse.subsection'),
        ),
    ]
