# Generated by Django 3.2 on 2022-05-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcourse', '0005_auto_20220516_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads_file_tcr/'),
        ),
    ]
