# Generated by Django 3.2 on 2022-05-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcourse', '0006_assignment_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcourse',
            old_name='subsection_id',
            new_name='sub_id',
        ),
    ]
