# Generated by Django 3.2.5 on 2022-01-08 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220108_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.classroom'),
        ),
    ]
