# Generated by Django 3.2.5 on 2022-01-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_attendance_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student_id',
        ),
    ]
