# Generated by Django 3.2.5 on 2022-01-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereq',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
