# Generated by Django 3.2 on 2022-02-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_attendancereq_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereq',
            name='closed_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendancereq',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
