# Generated by Django 3.2 on 2022-03-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_subcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcourse',
            name='file',
        ),
        migrations.AlterField(
            model_name='subcourse',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='SubCourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_file/')),
                ('subcourse_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subcourse')),
            ],
        ),
        migrations.AddField(
            model_name='subcourse',
            name='subsection_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subsection'),
        ),
    ]
