# Generated by Django 3.2 on 2022-03-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220328_0727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCourseFile',
        ),
    ]
