# Generated by Django 3.2 on 2022-04-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_delete_subcoursefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcourse',
            old_name='title',
            new_name='name',
        ),
    ]
